title: gilmar sales
description: >-
  Engenheiro de sistemas,
  estudando o que faz o
  <em>silício</em> cantar.
baseurl: ""
url: ""
author:
  name: Gilmar Sales
  email: gilmar_custodio_@hotmail.com
  profession: Eng. de Software
  city: Morrinhos
  country: GO
  description: Ciêntista da Computação pelo Instituto Federal Goiano.
social_links:
  github: gilmar-sales

paginate: 5
paginate_path: "/page/:num/"
max_pages: 5
# Build settings
plugins:
  - jekyll-feed
sass:
  style: compressed
  sass_dir: _sass
